import type { Metadata } from "next"
import { Montserrat } from "next/font/google"
import "./globals.css"
import { Toaster } from "react-hot-toast"
import Navbar from "@/components/navbar/Navbar"
import Provider from "./context/AuthContext"

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Provider>
        <body className={montserrat.className}>
          <Toaster />
          <Navbar />
          {children}
        </body>
      </Provider>
    </html>
  );
}
